routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Auths*/
Auth::routes();

/*Login*/
Route::get('/', function () {
    return view('auth.login');
});

/*Home*/
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

/*Medicamentos*/
Route::resource('medicamentos', 'MedicamentosController')->middleware('auth');
Route::post('/desactivar/{id}/{status}', 'MedicamentosController@desactivar');
Route::post('/activar/{id}/{status}', 'MedicamentosController@activar');
Route::post('/salida/medicamento/{id}', 'MedicamentosController@salida');

/*Categorias*/
Route::resource('categorias', 'CategoriasController')->middleware('auth');
Route::post('restaurar/categoria/{id}', 'CategoriasController@restaurar');

/*Pacientes*/
Route::resource('pacientes', 'PacientesController')->middleware('auth');
Route::post('/historia/{id}', 'PacientesController@historia');
Route::get('/descargar-ficha/{id}', 'PacientesController@historiaPDF')->name('pacientes.historiasPDF');
Route::get('/listado', 'PacientesController@list')->name('pacientes.list')->middleware('auth');
Route::post('/suspender-paciente/{id}/{status}', 'PacientesController@suspender');

/**/
Route::resource('solicitudes', 'SolicitudesController')->middleware('auth');
Route::post('/buscar/paciente/{ced}', 'SolicitudesController@buscarPaciente');
Route::post('/buscar/medicamentos/{id}', 'SolicitudesController@traer_m');

app/Paciente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Solicitud;

class Paciente extends Model
{
    protected $table = 'pacientes';

    protected $fillable = ['nacionalidad','cedula','nombres','apellidos','fec_nac','genero','telefono','correo','residencia','municipio'];

    public function Solicitudes()
    {
    	return $this->hasMany(Solicitud::class);
    }
}

app/Http/Controllers/PacientesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\support\Facades\Session;
use Illuminate\Http\Request;
use App\Paciente;
use App\Medicamento;
use Barryvdh\DomPDF\Facade as PDF;

class PacientesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
         $pacientes=Paciente::all();

         return view('pacientes.index', compact('pacientes'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['nacionalidad' => 'required', 'cedula' => 'required|unique:pacientes', 'nombres' => 'required', 'apellidos' => 'required|max:20', 'genero' => 'required','fec_nac' => 'required','telefono' => 'required|numeric', 'correo' => 'required','residencia' => 'required', 'municipio' => 'required'],['required' => 'Campo Requerido', 'unique' => 'Ya este paciente esta registrado!']);
        
        $paciente = new Paciente();
        $paciente->nacionalidad = $request->nacionalidad;
        $paciente->cedula = $request->cedula;
        $paciente->nombres = $request->nombres;
        $paciente->apellidos = $request->apellidos;
        $paciente->genero = $request->genero;
        $paciente->fec_nac = $request->fec_nac;
        $paciente->telefono = $request->telefono;
        $paciente->correo = $request->correo;
        $paciente->residencia = $request->residencia;
        $paciente->municipio = $request->municipio;
        $paciente->save();

        Session::flash('message','Se ha registrado exitosamente al Paciente: '.$request->nombres.' '.$request->apellidos.'!');
        Session::flash('class','success');

        return redirect('/pacientes');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $paciente = Paciente::find($id);
        $medicamento = Medicamento::all();
        return view('pacientes.show', compact('paciente', 'medicamento'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

        public function historia($id)
    {

          $paciente = Paciente::find($id);
          return $paciente;
        
    }

    public function historiaPDF($id)
    {
        $paciente = Paciente::find($id);
        
        $pdf = PDF::loadView('pdf.paciente', compact('paciente'));

        return $pdf->stream('listado');
    }

    public function list()
    {
        $pacientes = Paciente::all();
        return view('pacientes.list', compact('pacientes'));
    }

    public function suspender($id,$status)
    {
          
        $sts = $status;  

        $paciente = Paciente::find($id);
        $paciente->status = $status;
        $paciente->save();

        if ($sts == 1) {

         Session::flash('message','Se ha Suspendido al Paciente: '.$paciente->nombres.' '.$paciente->apellidos.'!');
         Session::flash('class','info');

        }else{

          Session::flash('message','Se ha Activado al Paciente: '.$paciente->nombres.' '.$paciente->apellidos.'!');
          Session::flash('class','success');
        }
        
        
    }
}

resources/views/pacientes/index.blade.php
@extends('layouts.admin')
@section('content')

         @if (session('message'))
          <div class="row purchace-popup">
            <div class="col-12">
              <p class="alert alert-{{ session('class') }} card-description">
                   {{ session('message') }}</p>
            </div>
          </div>
         @endif

<div class="row">
<div class="col-md-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Registro de Pacientes</h4>
                  <form class="form-sample" action="{{ route('pacientes.store') }}" method="POST">

                    @csrf
                    <p class="alert alert-info">
                      Por favor ingresar la informacion personal del paciente.
                    </p>

                    <div class="row">
                        <div class="form-group col-md-6">
                          <label for="exampleInputName1">Nacionalidad</label>
                          <select class="form-control{{ $errors->has('nacionalidad') ? ' is-invalid' : '' }}" name='nacionalidad' >
                                  <option selected="selected" disabled="disabled">-- Seleccione --</option>
                                  <option value="V" {{ old('nacionalidad') == 'V' ? 'selected' : '' }}>V</option>
                                  <option value="E" {{ old('nacionalidad') == 'E' ? 'selected' : '' }}>E</option>
                          </select>
                          @if ($errors->has('nacionalidad'))
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('nacionalidad') }}</strong>
                                </span>
                               @endif

                          
                        </div>
                        <div class="form-group col-md-6">
                          <label for="exampleInputName1">Cedula</label>
                          <input type="number" min="1" maxlength="8" value="{{ old('cedula') }}" name="cedula" class="form-control{{ $errors->has('cedula') ? ' is-invalid' : '' }}">
                          @if ($errors->has('cedula'))
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('cedula') }}</strong>
                                </span>
                               @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                          <label for="exampleInputName1">Nombres</label>
                          <input type="text" name="nombres" value="{{ old('nombres') }}" class="form-control{{ $errors->has('nombres') ? ' is-invalid' : '' }}">
                          @if ($errors->has('nombres'))
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('nombres') }}</strong>
                                </span>
                               @endif

                          
                        </div>
                        <div class="form-group col-md-6">
                          <label for="exampleInputName1">Apellidos</label>
                          <input type="text" name="apellidos" value="{{ old('apellidos') }}" class="form-control{{ $errors->has('apellidos') ? ' is-invalid' : '' }}">
                          @if ($errors->has('apellidos'))
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('apellidos') }}</strong>
                                </span>
                               @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                          <label for="exampleInputName1">Genero</label>
                          <select class="form-control{{ $errors->has('genero') ? ' is-invalid' : '' }}"  name="genero">
                              <option selected="selected" disabled="disabled">-- Seleccione --</option>

                              <option value="M" {{ old('genero') == 'M' ? 'selected' : '' }}>Masculino</option>
                              <option value="F" {{ old('genero') == 'F' ? 'selected' : '' }}>Femenino</option>

                            </select>
                          @if ($errors->has('genero'))
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('genero') }}</strong>
                                </span>
                               @endif

                          
                        </div>
                        <div class="form-group col-md-6">
                          <label for="exampleInputName1">Fecha de Nacimiento</label>
                          <input type="date" name="fec_nac" value="{{ old('fec_nac') }}" class="form-control{{ $errors->has('fec_nac') ? ' is-invalid' : '' }}">
                          @if ($errors->has('fec_nac'))
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('fec_nac') }}</strong>
                                </span>
                               @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                          <label for="exampleInputName1">Telefono</label>
                          <input type="number" class="form-control{{ $errors->has('telefono') ? ' is-invalid' : '' }}"  min="11" placeholder="04100000000" value="{{ old('telefono') }}" name="telefono">
                          @if ($errors->has('genero'))
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('genero') }}</strong>
                                </span>
                               @endif

                          
                        </div>
                        <div class="form-group col-md-6">
                          <label for="exampleInputName1">Correo Electronico</label>
                          <input type="email" value="{{ old('correo') }}" class="form-control{{ $errors->has('correo') ? ' is-invalid' : '' }}"  name="correo">
                          @if ($errors->has('correo'))
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('correo') }}</strong>
                                </span>
                               @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                          <label for="exampleInputName1">Residencia</label>
                          <input type="text" name="residencia" value="{{ old('residencia') }}" class="form-control{{ $errors->has('residencia') ? ' is-invalid' : '' }}">
                          @if ($errors->has('residencia'))
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('residencia') }}</strong>
                                </span>
                               @endif

                          
                        </div>
                        <div class="form-group col-md-6">
                          <label for="exampleInputName1">Municipio</label>
                          <input type="text" name="municipio" value="{{ old('municipio') }}" class="form-control{{ $errors->has('municipio') ? ' is-invalid' : '' }}">
                          @if ($errors->has('municipio'))
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('municipio') }}</strong>
                                </span>
                               @endif
                        </div>
                    </div>
                    <div class="col-md-12 text-center">
                    <button type="submit" class="btn btn-success mr-2">Guardar</button>
                    <button class="btn btn-light">Cancelar</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>

<div class="col-lg-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Pacientes Registrados</h4>
                  <p class="card-description">
                    Listado de Pacientes inscritos en la Oficina de Atencion al Ciudadano.
                  </p>
                  <div class="table-responsive">
                    <table id="example1" class="table table-striped table-hover" style="width:100%">
                      <thead>
                        <tr>
                          <th>Nro</th>
                          <th>Paciente</th>
                          <th>Estado</th>
                          <th>Historia</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($pacientes as $paciente)
                        
                         <tr>
                          <td>{{ $loop->iteration }}</td>
                          <td>{{ $paciente->nombres }}</td>
                          <td><label class="text-primary" >Activo</label></td>
                          <td><label class="text-primary" ><button class="btn btn-outline-info btn-sm" data-toggle="modal" data-target="#modal-secundary{{ $paciente->id }}"><i class="fa fa-list"></i></button></label></td>
                         </tr>

                        @endforeach
                      </tbody>
                    </table>
                </div>
                </div>
              </div>
 </div>
 </div>

 @foreach($pacientes as $paciente)
 <div class="modal modal-default fade" id="modal-secundary{{ $paciente->id }}">
          <div class="modal-dialog">
            <div class="modal-content" >
              <div class="modal-header">
                <h4>Ficha del Paciente: {{ $paciente->nombres.' '.$paciente->apellidos }}</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
              </div>
              <div class="modal-body" id="text">
                <div class="card">
                   <div class="card-body">
                <table class="table table-hover table-striped">
                  <tr class="text-center"><th colspan="2">Datos Personales</th></tr>
                  <tr><td>Identificacion: </td><td id="cedula">{{ $paciente->nacionalidad.'-'.$paciente->cedula }}</td></tr>
                  <tr><td>Nombre: </td><td id="nombre">{{ $paciente->nombres.' '.$paciente->apellidos }}</td></tr>
                  <tr><td>Sexo: </td><td id="genero">{{ $paciente->genero }}</td></tr>
                  <tr class="text-center"><th colspan="2">Datos de Ubicacion</th></tr>
                  <tr><td>Residencia: </td><td id="residencia">{{ $paciente->residencia }}</td></tr>
                  <tr><td>Municipio: </td><td id="municipio">{{ $paciente->municipio }}</td></tr>
                  <tr class="text-center"><th colspan="2">Datos de Contacto</th></tr>
                  <tr><td>Telefono: </td><td id="telefono">{{ $paciente->telefono }}</td></tr>
                  <tr><td>Correo: </td><td id="correo">{{ $paciente->correo }}</td></tr>
                </table>
                </div>
                </div>
              </div>
              <div class="modal-footer">
                <a href="{{ route('pacientes.historiasPDF',$paciente->id) }}" class="btn btn-primary btn-outline-dark">PDF</a>
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Cerrar</button>
              </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
  </div>
        <!-- /.modal --> 
@endforeach

@endsection

resources/views/pacientes/list.blade.php
@extends('layouts.admin')
@section('content')

@if (session('message'))
          <div class="row purchace-popup">
            <div class="col-12">
              <p class="alert alert-{{ session('class') }} card-description">
                   {{ session('message') }}</p>
            </div>
          </div>
@endif

<div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Listado de Pacientes</h4>
                  <p class="card-description">
                    Listado de Pacientes inscritos en la Oficina de Atencion al Ciudadano.
                  </p>
                  <div class="table-responsive">
                    <table id="example1" class="table table-striped table-hover" style="width:100%">
                      <thead>
                        <tr>
                          <th>Nro</th>
                          <th>Identificacion</th>
                          <th>Paciente</th>
                          <th>Estado</th>
                          <th>Acciones</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($pacientes as $paciente)
                        
                         <tr>
                          <td>{{ $loop->iteration }}</td>
                          <td>{{ $paciente->nacionalidad.'-'.$paciente->cedula }}</td>
                          <td>{{ $paciente->nombres.' '.$paciente->apellidos }}</td>
                          <td>
                            @if($paciente->status == 0)
                            <label class="text-primary" >Activo</label></td>
                            @else
                            <label class="text-primary" >Desactivado</label></td>
                            @endif
                          <td>
                            <a class="btn btn-info btn-sm" href="{{ route('pacientes.show',$paciente->id) }}" title="Historia del Paciente"><i class="fa fa-vcard"></i></a>

                            @if($paciente->status == 0) 

                            <button class="btn btn-danger btn-sm" title="Suspender Paciente" onclick="suspender_paciente('{{ $paciente->id }}',1)"><i class="fa fa-exclamation-triangle"></i></button>

                            @else

                            <button class="btn btn-success btn-sm" title="Activar Paciente" onclick="suspender_paciente('{{ $paciente->id }}',0)"><i class="fa fa-check"></i></button>

                            @endif
                          </td>
                         </tr>

                        @endforeach
                      </tbody>
                    </table>
                </div>
                </div>
        </div>
 </div>
@endsection

resources/views/pacientes/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-md-12 text-left mb-3">
                  	<a class="btn btn-light btn-outline-dark" href="{{ route('pacientes.list') }}">Atras</a>
</div>
<div class="col-md-12 grid-margin stretch-card">

                  <div class="card">
                    <div class="card-body">
                      <blockquote class="blockquote blockquote-primary">
                    <h4 class="text-center">{{ $paciente->nacionalidad.'-'.$paciente->cedula.' '.$paciente->nombres.' '.$paciente->apellidos }}</h4>
                    <footer class="blockquote-footer text-center">Paciente inscrito en la Oficina de Atencion al Ciudadano desde {{ $paciente->created_at }}.
                    </footer>
                  </blockquote>
                      <h3 class="card-title text-center"></h3>
                      <p class="card-description text-center">
                        
                      </p>
                      
                      <h4 class="text-center mb-3">Informacion Personal</h4>
                      <table class="table table-hover table-primary mb-3">
                      		<tr>
                      			<th>Telefono:</th>
                      			<td>{{ $paciente->telefono }}</td>
                      			<th>Correo:</th>
                      			<td>{{ $paciente->correo }}</td>
                      		</tr>
                      		<tr>
                      			<th>Municipio:</th>
                      			<td>{{ $paciente->municipio }}</td>
                      			<th>Residencia:</th>
                      			<td>{{ $paciente->residencia }}</td>
                      		</tr>
                      </table>

                      <h4 class="text-center mb-3">Solicitudes Procesadas</h4>

                      <table class="table table-hover table-success mb-3">
                      		
                      			<th>#</th>
                            <th>Fecha de Solicitud</th>
                            <th>Medicamento Solicitado</th>
                      			<th>Cantidad Solicitada</th>
                      			<th>Detalle</th>
                      			<th>Status</th>
                      		
                      		<tbody>
                      			@foreach($paciente->Solicitudes as $sol)
                      			<tr>
                      				<td>{{ $loop->iteration }}</td>
                              <td>{{ $sol->created_at }}</td>
                              <td>{{ $sol->buscarMedicamento($sol->medicamento_id) }}</td>
                      				<td>{{ $sol->cantidad }}</td>
                      				<td>{{ $sol->detalle }}</td>
                      				@if($sol->status == 1)

                      				<td><span class="badge badge-primary">Procesada</span></td>

                      				@else
                                     
                                    <td><span class="badge badge-danger">No Aprobada</span></td>

                      				@endif
                      			</tr>
                      			@endforeach
                      		</tbody>
                      </table>
                    </div>
                  </div>
                  
</div>
@endsection