routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Auths*/
Auth::routes();

/*Login*/
Route::get('/', function () {
    return view('auth.login');
});

/*Home*/
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

/*Medicamentos*/
Route::resource('medicamentos', 'MedicamentosController')->middleware('auth');
Route::post('/desactivar/{id}/{status}', 'MedicamentosController@desactivar');
Route::post('/activar/{id}/{status}', 'MedicamentosController@activar');
Route::post('/salida/medicamento/{id}', 'MedicamentosController@salida');

/*Categorias*/
Route::resource('categorias', 'CategoriasController')->middleware('auth');
Route::post('restaurar/categoria/{id}', 'CategoriasController@restaurar');

/*Pacientes*/
Route::resource('pacientes', 'PacientesController')->middleware('auth');
Route::post('/historia/{id}', 'PacientesController@historia');
Route::get('/descargar-ficha/{id}', 'PacientesController@historiaPDF')->name('pacientes.historiasPDF');
Route::get('/listado', 'PacientesController@list')->name('pacientes.list')->middleware('auth');
Route::post('/suspender-paciente/{id}/{status}', 'PacientesController@suspender');

/**/
Route::resource('solicitudes', 'SolicitudesController')->middleware('auth');
Route::post('/buscar/paciente/{ced}', 'SolicitudesController@buscarPaciente');
Route::post('/buscar/medicamentos/{id}', 'SolicitudesController@traer_m');

app/Medicamento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Categoria;
use App\Medicamento;

class Medicamento extends Model
{
    protected $table = 'medicamentos';

    protected $fillable = ['categoria_id','name','descripcion','existencia'];

    public function Categoria()
    {
    	return $this->belongsTo(Categoria::class);
    }

     public function identificar($id)
    {
    	$name = Medicamento::find($id);
    	return $name;
    }
}

app/Http/Controllers/MedicamentosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Categoria;
use App\Medicamento;
use App\Movimiento;
use Illuminate\Support\Facades\Session;

class MedicamentosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categorias = Categoria::where('status',1)->get();
        $medicamentos = Medicamento::where('status',1)->get();
        return view('medicamentos.index', compact('categorias','medicamentos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $medicamentos = Medicamento::all();
        return view('medicamentos.almacen', compact('medicamentos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['categoria_id' => 'required', 'name' => 'required|min:4|max:20|unique:medicamentos', 'existencia' => 'required'], ['categoria_id.required' => 'Categoria es Obligatoria', 'name.required' => 'Nombre es Obligatorio', 'name.min' => 'Longitud Minima 4 Caracteres', 'name.max' => 'Longitud Maxima 20 Caracteres', 'name.unique' => 'Este medicamento ya existe en almacen', 'existencia.required' => 'Cantidad de Existencia es Obligatoria']);

        $medicamento = new Medicamento();
        $medicamento->categoria_id = $request->categoria_id;
        $medicamento->name = $request->name;
        $medicamento->descripcion = $request->descripcion;
        $medicamento->existencia = $request->existencia;
        $medicamento->save();

        $Categoria = Categoria::find($request->categoria_id);

        $movimiento = new Movimiento();
        $movimiento->medicamento_id = $medicamento->id;
        $movimiento->tipo_mov = 'I';
        $movimiento->detalle_mov = 'Ingreso del Medicamento: '.$request->name.' en la Categoria: '.$Categoria->name;
        $movimiento->cantidad = $request->existencia;
        $movimiento->save();

        Session::flash('message','Se ha creado el Medicamento: '.$request->name.'!');
        Session::flash('class','success');

        return redirect('/medicamentos');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categorias = Categoria::where('status',1)->get();
        $medicamento = Medicamento::find($id);

        return view('medicamentos.edit', compact('medicamento','categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //$request->validate(['existencia' => 'required']);

        $medicamento = Medicamento::find($id);
        $name = $medicamento->name;
        $medicamento->existencia = ($medicamento->existencia+$request->existencia);
        $medicamento->save();

        $movimiento = new Movimiento();
        $movimiento->medicamento_id = $medicamento->id;
        $movimiento->tipo_mov = 'E';
        $movimiento->detalle_mov = 'Recepcion del Medicamento: '.$medicamento->name.' en la Categoria: '.$medicamento->Categoria->name;
        $movimiento->cantidad = $request->existencia;
        $movimiento->save();

        Session::flash('message','Se ha recargo el stock medicamento: '.$name.'!');
        Session::flash('class','success');
        
        return redirect('/medicamentos/create');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function desactivar($id,$status)
    {
        
        $medicamento = Medicamento::find($id);
        $medicamento->status = $status;
        $medicamento->save();


        //return $id.'aa'.$status;

    }

    public function activar($id,$status)
    {
        $medicamento = Medicamento::find($id);
        $medicamento->status = $status;
        $medicamento->save();
    }

    public function salida(Request $request, $id)
    {
        
        $medicamento = Medicamento::find($id);
        $name = $medicamento->name;
        $medicamento->existencia = ($medicamento->existencia-$request->cantidad);
        $medicamento->save();

        $movimiento = new Movimiento();
        $movimiento->medicamento_id = $medicamento->id;
        $movimiento->tipo_mov = 'S';
        $movimiento->detalle_mov = 'Salida del Medicamento: '.$medicamento->name.' en la Categoria: '.$medicamento->Categoria->name;
        $movimiento->cantidad = $request->cantidad;
        $movimiento->save();

        Session::flash('message','Se ha procesado una Salida de Almacen del medicamento: '.$name.'!');
        Session::flash('class','success');
        
        return redirect('/medicamentos/create');
     
    }
}

resources/views/medicamentos/almacen.blade.php
@extends('layouts.admin')
@section('content')

         @if (session('message'))
          <div class="row purchace-popup">
            <div class="col-12">
              <p class="alert alert-{{ session('class') }} card-description">
                   {{ session('message') }}</p>
            </div>
          </div>
         @endif

<div class="row">
 <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Almacen de Medicamentos</h4>
                  <p class="card-description">
                    En esta seccion puedes encontrar todos los medicamentos que se han registrado en sistema.
                  </p>
                  <div class="table-responsive">
                    <table id="example1" class="table table-striped table-hover" style="width:100%">
                      <thead>
                        <tr>
                          <th>Nro</th>
                          <th>Medicamento</th>
                          <th>Categoria</th>
                          <th>Stock</th>
                          <th>Ultima Recepcion</th>
                          <th>Acciones</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($medicamentos as $medicamento)
                        
                         <tr>
                         	<td>{{ $loop->iteration }}</td>
                          <td>{{ $medicamento->name }}</td>
                          <td>{{ $medicamento->Categoria->name }}</td>
                          <td>{{ $medicamento->existencia }}</td>
                          <td>{{ $medicamento->updated_at }}</td>
                          <td>
                            @if($medicamento->status==1)
                            <a class="btn btn-primary" title="Recargar Medicamento" href="{{ route('medicamentos.edit',$medicamento->id) }}" ><i class="fa fa-plus"></i></a> 
                            @else
                            <button class="btn btn-primary" disabled="disabled" title="No Disponible, Debe activar"><i class="fa fa-plus"></i></button> 
                            @endif

                            @if($medicamento->status==1) 
                            <a class="btn btn-danger" onclick="desactivar('{{$medicamento->id}}',0)" title="Desactivar Medicamento"><i class="fa  fa-thumbs-o-down"></i></a>
                            @else
                            <button class="btn btn-success" onclick="activar('{{$medicamento->id}}',1)" title="Activar Medicamento"><i class="fa  fa-thumbs-o-up"></i></button>
                            @endif

                            @if($medicamento->status==1) 
                            <a class="btn btn-warning" data-toggle='modal' data-target="#modal{{$medicamento->id}}" title="Salida de Almacen"><i class="fa  fa-mail-forward"></i></a>
                            @else
                            <button class="btn btn-warning" disabled="disabled" title="Salida de Almacen/No Disponible"><i class="fa  fa-mail-forward"></i></button>
                            @endif
                          </td>
                         </tr>

                        @endforeach
                      </tbody>
                    </table>
                </div>
                </div>
              </div>
 </div>
 </div>

    @foreach($medicamentos as $medicamento)
    <div class="modal fade" tabindex="-1" role="dialog" id="modal{{$medicamento->id}}">
        <div class="modal-dialog" role="document">
         <div class="modal-content">
         <div class="modal-header">
              <h5 class="modal-title">Salida Medicamento: {{$medicamento->name}}</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
         </div>
         <div class="modal-body" id="body">
         <form class="forms-sample" action="{{ action('MedicamentosController@salida',$medicamento->id) }}" method="POST">
            @csrf
                <div class="form-group">
                    <label for="exampleInputPassword1">Cantidad a Sacar:</label>
                    <input type="number" min="1" class="form-control"  name="cantidad" placeholder="1,2,3..." required="required">
               </div>
         </div>
         <div class="modal-footer">
             <button type="submit" class="btn btn-primary">Procesar Recarga</button>
             <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
         </div>
    </form>
        </div>
       </div>
    </div>
    @endforeach
@endsection

resources/views/medicamentos/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="col-md-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Recargar Medicamento: {{ $medicamento->name }} </h4>
                  <form class="forms-sample" action="{{ route('medicamentos.update',$medicamento->id) }}" method="POST">
                   
                   <input type="hidden" name="_method" value="PUT">
                   <input type="hidden" name="_token" value="{{ csrf_token()}}">

                    <div class="form-group row">
                          <label class="col-sm-3 col-form-label">Categoria: </label>
                          <div class="col-sm-9">
                            <select class="form-control{{ $errors->has('categoria_id') ? ' is-invalid' : '' }}" name="categoria_id" value="{{ old('categoria_id') }}" disabled="disabled">
                              <option selected="selected" disabled="disabled">{{ $medicamento->Categoria->name }}</option>
                              @foreach($categorias as $categoria)
                              <option value="{{ $categoria->id }}">{{ $categoria->name }}</option>
                              @endforeach
                            </select>
                          </div>
                          <div class="col-sm-12">
                          	@if ($errors->has('categoria_id'))
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('categoria_id') }}</strong>
                            </span>
                           @endif
                          </div>
                     </div>
                          
                    <div class="form-group">
                      <label for="exampleInputEmail3">Nombre del Medicamento:</label>
                      <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="exampleInputEmail3" placeholder="Nombre..." value="{{ $medicamento->name }}" disabled="disabled">
                      @if ($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                            </span>
                           @endif
                    </div>

                     <div class="form-group">
                      <label for="exampleInputPassword4">Descripcion:</label>
                      <textarea name="descripcion" class="form-control{{ $errors->has('descripcion') ? ' is-invalid' : '' }}" placeholder="Especifique las caracteristicas del medicamento..." disabled="disabled">{{ $medicamento->descripcion }}</textarea>
                           @if ($errors->has('descripcion'))
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('descripcion') }}</strong>
                            </span>
                           @endif
                     </div>
                     <p class="alert alert-primary">Hey! Acontinuacion se detalla la cantidad actual que existe en Almacen.</p>
                     <div class="row">



                     <div class="form-group col-6 text-center">
                      <label for="exampleInputCity1">Cantidad en Almacen:</label>
                      <input type="number" class="form-control{{ $errors->has('existencia') ? ' is-invalid' : '' }}" id="exampleInputCity1" placeholder="Disponibilidad" value="{{ $medicamento->existencia }}" disabled="disabled">

                           @if ($errors->has('existencia'))
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('existencia') }}</strong>
                            </span>
                           @endif
                      </div>

                     <div class="form-group col-6 text-center">
                      <label for="exampleInputCity1">Cantidad que se añadira:</label>
                      <input name="existencia" type="number" class="form-control{{ $errors->has('existencia') ? ' is-invalid' : '' }}" id="exampleInputCity1" placeholder="Disponibilidad">

                           @if ($errors->has('existencia'))
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('existencia') }}</strong>
                            </span>
                           @endif
                      </div>
                     </div>
                    <div class="col-lg-12 text-center">
                    <button type="submit" class="btn btn-success mr-2">Recargar Medicamento</button>
                    <a class="btn btn-light" href="{{ route('medicamentos.create') }}">Atras</a>
                    </div>
                  </form>
                </div>
              </div>
</div>
@endsection

resources/views/medicamentos/index.blade.php
@extends('layouts.admin')
@section('content')

         @if (session('message'))
          <div class="row purchace-popup">
            <div class="col-12">
              <p class="alert alert-{{ session('class') }} card-description">
                   {{ session('message') }}</p>
            </div>
          </div>
         @endif

<div class="row">
<div class="col-md-5 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Registro de Medicamentos</h4>
                  <p class="card-description alert alert-info text-justify">
                    Esta seccion permite el ingreso de medicamentos que no existen aun en el almacen de medicamentos. Antes de procesar el ingreso verifica en los medicamentos disponibles.
                  </p>
                  <form class="forms-sample" action="{{ route('medicamentos.store') }}" method="POST">
                   
                   @csrf

                    <div class="form-group row">
                          <label class="col-sm-3 col-form-label">Categoria: </label>
                          <div class="col-sm-9">
                            <select class="form-control{{ $errors->has('categoria_id') ? ' is-invalid' : '' }}" name="categoria_id" value="{{ old('categoria_id') }}">
                              <option selected="selected" disabled="disabled">-- Seleccione --</option>
                              @foreach($categorias as $categoria)
                              <option value="{{ $categoria->id }}">{{ $categoria->name }}</option>
                              @endforeach
                            </select>
                          </div>
                          <div class="col-sm-12">
                          	@if ($errors->has('categoria_id'))
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('categoria_id') }}</strong>
                            </span>
                           @endif
                          </div>
                     </div>
                          
                    <div class="form-group">
                      <label for="exampleInputEmail3">Nombre del Medicamento:</label>
                      <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="exampleInputEmail3" placeholder="Nombre..." value="{{ old('name') }}">
                      @if ($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                            </span>
                           @endif
                    </div>

                     <div class="form-group">
                      <label for="exampleInputPassword4">Descripcion:</label>
                      <textarea name="descripcion" class="form-control{{ $errors->has('descripcion') ? ' is-invalid' : '' }}" placeholder="Especifique las caracteristicas del medicamento..." value="{{ old('descripcion') }}"></textarea>
                           @if ($errors->has('descripcion'))
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('descripcion') }}</strong>
                            </span>
                           @endif
                     </div>

                     <div class="form-group text-center">
                      <label for="exampleInputCity1">Cantidad de Ingreso</label>
                      <input name="existencia" type="number" class="form-control{{ $errors->has('existencia') ? ' is-invalid' : '' }}" id="exampleInputCity1" placeholder="Disponibilidad" value="{{ old('existencia') }}">

                           @if ($errors->has('existencia'))
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('existencia') }}</strong>
                            </span>
                           @endif
                      </div>

                    <div class="col-lg-12 text-center">
                    <button type="submit" class="btn btn-success mr-2">Guardar</button>
                    <button class="btn btn-light" type="reset">Cancelar</button>
                    </div>
                  </form>
                </div>
              </div>
 </div>
 <div class="col-lg-7 grid-margin stretch-card">
              <div class="card alert-success">
                <div class="card-body">
                  <h4 class="card-title">Medicamentos Disponibles</h4>
                  <p class="card-description">
                    Listado de medicamentos existentes en almacen.
                  </p>
                  <div class="table-responsive">
                    <table id="example1" class="table table-striped table-hover" style="width:100%">
                      <thead>
                        <tr>
                          <th>Nro</th>
                          <th>Medicamento</th>
                          <th>Estado</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($medicamentos as $medicamento)
                        
                         <tr>
                         	<td>{{ $loop->iteration }}</td><td>{{ $medicamento->name }}</td><td><label class="text-primary" >Dispobible</label></td>
                         </tr>

                        @endforeach
                      </tbody>
                    </table>
                </div>
                </div>
              </div>
 </div>
 </div>

@endsection