routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Auths*/
Auth::routes();

/*Login*/
Route::get('/', function () {
    return view('auth.login');
});

/*Home*/
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

/*Medicamentos*/
Route::resource('medicamentos', 'MedicamentosController')->middleware('auth');
Route::post('/desactivar/{id}/{status}', 'MedicamentosController@desactivar');
Route::post('/activar/{id}/{status}', 'MedicamentosController@activar');
Route::post('/salida/medicamento/{id}', 'MedicamentosController@salida');

/*Categorias*/
Route::resource('categorias', 'CategoriasController')->middleware('auth');
Route::post('restaurar/categoria/{id}', 'CategoriasController@restaurar');

/*Pacientes*/
Route::resource('pacientes', 'PacientesController')->middleware('auth');
Route::post('/historia/{id}', 'PacientesController@historia');
Route::get('/descargar-ficha/{id}', 'PacientesController@historiaPDF')->name('pacientes.historiasPDF');
Route::get('/listado', 'PacientesController@list')->name('pacientes.list')->middleware('auth');
Route::post('/suspender-paciente/{id}/{status}', 'PacientesController@suspender');

/**/
Route::resource('solicitudes', 'SolicitudesController')->middleware('auth');
Route::post('/buscar/paciente/{ced}', 'SolicitudesController@buscarPaciente');
Route::post('/buscar/medicamentos/{id}', 'SolicitudesController@traer_m');

app/Categoria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Medicamento;

class Categoria extends Model
{
   
   protected $table = 'categorias';

   protected $fillable = ['name'];

   public function Medicamentos()
   {
   	
    return $this->hasMany(Medicamento::class);

   }


}

app/Http/Controllers/CategoriasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Categoria;
use Illuminate\Support\Facades\Session;

class CategoriasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categorias = Categoria::where('status',1)->get();
        $categoriasD = Categoria::where('status',0)->get();

        return view('categorias.index', compact('categorias','categoriasD'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         
        $request->validate(['name' => 'required|min:4|max:20|unique:categorias'],['name.required' => 'El nombre es Obligatorio', 'name.min' => 'Longitud Minima 4 Caracteres', 'name.max' => 'Longitud Maxima de 20 Caracteres', 'name.unique' => 'Ya esta categoria existe, verifique los listados.']);
       
        $category = new Categoria();
        $category->name = $request->name;
        $category->save();

        Session::flash('message','Se ha creado un registro.!');
        Session::flash('class','success');

        return redirect('/categorias');

 

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $categoria = Categoria::find($id);
        $name = $categoria->name;
        $categoria->status = '0';
        $categoria->save();

        Session::flash('message','Se ha Eliminado: '.$name);
        Session::flash('class','success');

    }

        public function restaurar($id)
    {
        $categoria = Categoria::find($id);
        $name = $categoria->name;
        $categoria->status = '1';
        $categoria->save();

        Session::flash('message','Se Restauro: '.$name);
        Session::flash('class','success');

    }

}

resources/views/categorias/index.blade.php
@extends('layouts.admin')
@section('content')

         @if (session('message'))
          <div class="row purchace-popup">
            <div class="col-12">
              <p class="alert alert-{{ session('class') }} card-description">
                   {{ session('message') }}</p>
            </div>
          </div>
         @endif

<div class="row">

            <div class="col-md-4 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Crear Categoria</h4>
                  <p class="alert alert-info card-description">
                   Las categorias sirven para clasificar los medicamentos.
                  </p>
                  <form id="category" class="forms-sample" action="{{ route('categorias.store') }}" method="POST">
                  	@csrf
                    <div class="form-group">
                      <label for="exampleInputName1">Ingrese Nombre</label>
                      <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" name="name" value="{{ old('name') }}" placeholder="ingresar el nombre de la categoria...">

                      @if ($errors->has('name'))
                            <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                      @endif

                    </div>
                    <div class="card-footer text-center">
                    <button type="submit" class="btn btn-success mr-2">Guardar</button>
                    <button class="btn btn-danger">Cancelar</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>

             <div class="col-lg-8 grid-margin stretch-card">
              <div class="card alert-success">
                <div class="card-body">
                  <h4 class="card-title">Categorias Disponibles</h4>
                  <p class="card-description">
                    Cada categoria tiene una coleccion de medicamentos asociada.
                  </p>
                    <table id="example1" class="table table-striped table-hover" style="width:100%">
                      <thead>
                        <tr>
                          <th>Nro</th>
                          <th>Categoria</th>
                          <th>Acciones</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($categorias as $categoria)
                        
                         <tr>
                         	<td>{{ $loop->iteration }}</td><td>{{ $categoria->name }}</td><td><button title="Eliminar" class="btn  btn-danger" onclick="desactivarCategoria('{{ $categoria->id }}','{{ $categoria->name }}')"><i class="fa fa-close"></i></button></td>
                         </tr>

                        @endforeach
                      </tbody>
                    </table>
                </div>
              </div>
            </div>
             
           <hr>

            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Categorias Desactivadas</h4>
                  <p class="card-description">
                    Estas categorias no estan disponibles para asociar con los medicamentos. Para habilitarlas oprima en "Restaurar".
                  </p>
                    <table id="example2" class="table table-striped table-hover" style="width:100%">
                      <thead>
                        <tr>
                          <th>Nro</th>
                          <th>Categoria</th>
                          <th>Acciones</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($categoriasD as $categoria)
                        
                         <tr>
                          <td>{{ $loop->iteration }}</td><td>{{ $categoria->name }}</td><td><button title="restaurar" class="btn  btn-primary" onclick="restaurar('{{ $categoria->id }}')"><i class="fa fa-refresh"></i></button></td>
                         </tr>

                        @endforeach
                      </tbody>
                    </table>
                </div>
              </div>
            </div>
</div>
@endsection